name: Texturepack-CI/CD

on:
  workflow_dispatch:
    inputs:
      texturepack_link:
        description: 'Link to texturepack'     
        required: true
        default: 'https://storage.googleapis.com/gaimcraft/resourcepacks/gaimcraft_resourcepack.zip'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
name: checkout
      uses: actions/checkout@v3
name: write changes to a file"
      run: echo "${{ github.event.inputs.texturepack_link}}" > resourse-pack-link.txt
name: stage changed files
      run: |
       git config --global user.email "github-actions@fuck.com"
       git config --global user.name "Link Updater"
       git add resourse-pack-link.txt &&
       git commit -m "Update link in file" &&
       git fetch &&
       git push